# Generated by Django 4.1.1 on 2022-09-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('balance', models.IntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
            ],
        ),
    ]
