# Generated by Django 4.1.1 on 2022-09-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_bill_customer_balance_delete_balance_bill_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
    ]
