# Generated by Django 4.1.1 on 2022-09-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
