# Generated by Django 4.1.1 on 2022-09-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_delete_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('site_id', models.CharField(max_length=200)),
                ('bill_id', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=8)),
                ('creation', models.CharField(max_length=100)),
                ('expiration', models.CharField(max_length=100)),
                ('pay_url', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('response', models.JSONField()),
                ('alt_url', models.CharField(blank=True, max_length=200)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
