# Generated by Django 4.1.1 on 2022-09-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
